### ISSUE TITLE
License

### ISSUE THREAD

**Issue by atv2016** [chenxiaoqino/udp-image-streaming#1]
Hi Chen Xiaoqino,
I was referred to your conversion of Richard's udp image streaming video.
I'm creating an issue because i don't know what your email address is.

A few questions:
-How is the latency
-Does it do both unicast and multicast, and does it use opencv for that or does it use separate network code. I see multicast references but the server doesn't seem to have any arguments other then port.
-If it's all the same to you, would you mind changing the license to a MIT license? I would like to use this (and will credit you) but with the GPL ambigous legal terms i'd rather not use that in my other code.

Thanks a lot.
atv2016

**Comment by atv2016** [comment]
Also - does it support audio as with Richard's code, and if not can we add this?

**Comment by atv2016** [comment]
Could we include audio (maybe port audio), something like this https://github.com/mofarrell/p2pvc and stuff like echo cancellation, http streaming, NAT traversal, record the video being received or streamed Also compatibility with being able to open the stream in VLC maybe (but that's not a necessity).

I don't mind paying you for these things, if you want?

**Comment by chenxiaoqino** [comment]
Hi, I've changed the license to MIT as I also want more involvement from commercial software side :-)
