### ISSUE TITLE
Tried this program. It works well within same PC. But doesnt work in two PCs

### ISSUE THREAD

**Issue by GovindKamathGitHub** [chenxiaoqino/udp-image-streaming#11]
I have tried to run the same program in two different machines. Client in one PC and server program in another PC. However it doesnt work. Does this program support multiple PCs? If so, what modification is required. Tried below trial.
In PC1:
Client 192.168.12 9999

In PC2:
Server 9999 (No response)

**Comment by chenxiaoqino** [comment]
Hi Govind,

IP should be 192.168.1.2 instead of 192.168.12? Also, please start server
before client.

Cheers,
--
Yours sincerely, Xiaoqi Chen
cxqn.info

**Comment by GovindKamathGitHub** [comment]
Hi,

Yes. I am providing the correct IP of the machine. Below is the correct usage I am trying in windows 10 PC. 

In PC1:
Client.exe 10.79.194.56 9999

In PC2:
Server.exe 9999

**Client PC Snapshot:**
![image](https://user-images.githubusercontent.com/53139524/61606069-293cc180-ac66-11e9-97b9-8ee8d338aa83.png)

Server PC Snapshot:

![image](https://user-images.githubusercontent.com/53139524/61606095-440f3600-ac66-11e9-806c-21dc04ca4727.png)

Do you know how to debug this in wireshark tool or any other mechanism?

Thanks for your help,
Govind

**Comment by chenxiaoqino** [comment]
You can first use "nc -l -u -p 9999" and "nc -u 10.79.194.56 9999" to debug
connectivity and make sure the port is reachable. If that's the case, it's
likely an OpenCV issue; otherwise it's a network/firewall issue.

Also, this program has no congestion control, so it will work only if you
have enough bandwidth between the two hosts. Try in LAN first.
--
Yours sincerely, Xiaoqi Chen
cxqn.info

**Comment by GovindKamathGitHub** [comment]
Thank you.  I will try this option for debugging.

**Comment by GovindKamathGitHub** [comment]
Hi,

Whether this program works directly in two PCs without any modifications? I dont know much about UDP communication, so struggling for modifications for my requirements.

Thanks,
Govind

**Comment by GovindKamathGitHub** [comment]
Hi,

Sorry. Firewall was the issue. It is working now. Very useful program. Thank you very much for your support.

Thanks,
Govind
