### ISSUE TITLE
Opencv assertion failed

### ISSUE THREAD

**Issue by atv2016** [chenxiaoqino/udp-image-streaming#3]
After running it for a long time, the client crashed with the following:

13291   effective FPS:67.8564   kbps:6514.22
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/imgproc/src/imgwarp.cpp, line 1968
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/imgproc/src/imgwarp.cpp:1968: error: (-215) ssize.area() > 0 in function resize

14737Abort trap: 6

I saw some google reports that this might be because the frame or image was empty:
http://stackoverflow.com/questions/21581858/c-opencv-assertion-failed-in-resize

**Comment by atv2016** [comment]
typo

**Comment by chenxiaoqino** [comment]
If this happened at server side, this may die to packet lost causing
decoding failure. Should add integrity check before displaying the image.

## 

Xiaoqi, sent from phone

**Comment by atv2016** [comment]
Well it was the client binary (but your logic makes sense, might be something similar)
17911   effective FPS:50.8156   kbps:4878.3
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/imgproc/src/imgwarp.cpp, line 1968
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/imgproc/src/imgwarp.cpp:1968: error: (-215) ssize.area() > 0 in function resize

19679Abort trap: 6
Zeus:udp-image-streaming-master alefveld$ ./client 192.168.0.19 10001

**Comment by chenxiaoqino** [comment]
Added in  899bb66 .

**Comment by atv2016** [comment]
Hey Danny,
Did this fix the issue? What was the issue?
I think the server used size() instead of Size as the client did?

I think one is for a 2d matrix and the other for 3D mat?

**Comment by chenxiaoqino** [comment]
Size() was a typo. I'm pretty sure it fixes the assertion failure, but in
case the picture become frozen after a long time, it may be a camera
capturing issue...

## 

Xiaoqi, sent from phone
