### ISSUE TITLE
Error in making Demo

### ISSUE THREAD

**Issue by rehofman** [chenxiaoqino/udp-image-streaming#5]
Hello, I get the following error when I try to make the demo:

rehofman@Reto-Ubuntu:~/UDPStream/udp-image-streaming$ cmake . && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rehofman/UDPStream/udp-image-streaming
[ 25%] Building CXX object CMakeFiles/client.dir/PracticalSocket.cpp.o
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp: In constructor ‘SocketException::SocketException(const string&, bool)’:
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp:50:38: error: ‘strerror’ was not declared in this scope
     userMessage.append(strerror(errno));
                                      ^
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp: In function ‘void fillAddr(const string&, short unsigned int, sockaddr_in&)’:
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp:64:32: error: ‘memset’ was not declared in this scope
   memset(&addr, 0, sizeof(addr));  // Zero out address structure
                                ^
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp: In member function ‘void Socket::setLocalPort(short unsigned int)’:
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp:136:42: error: ‘memset’ was not declared in this scope
   memset(&localAddr, 0, sizeof(localAddr));
                                          ^
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp: In member function ‘void UDPSocket::disconnect()’:
/home/rehofman/UDPStream/udp-image-streaming/PracticalSocket.cpp:308:40: error: ‘memset’ was not declared in this scope
   memset(&nullAddr, 0, sizeof(nullAddr));
                                        ^
make[2]: **\* [CMakeFiles/client.dir/PracticalSocket.cpp.o] Error 1
make[1]: **\* [CMakeFiles/client.dir/all] Error 2
make: **\* [all] Error 2

What am I doing wrong?

**Comment by rehofman** [comment]
solved it: needed to add #include <string.h> to PracticalSocket.cpp

**Comment by chenxiaoqino** [comment]
Which #include file? (Feel free to make a one-line pull request!)

## 

Xiaoqi, sent from phone

**Comment by rehofman** [comment]
#include<string.h>

**Comment by rehofman** [comment]
string.h, if I put it in brackets it gets deleted
