### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by rneupane93** [chenxiaoqino/udp-image-streaming#6]
Hey there!
Is there a way I can have the client forward the packets received from the server to a new client (the first client may behave as a server to this client)? Like port forwarding..
Something like A to B to C and that video is played at C and not B. Is there any suggestions that you can give? Not sure which command can do this work in sockets. 
Thanks!! :D

**Comment by chenxiaoqino** [comment]
Hi there,
You can try using "socat" command directly for port forwarding.
If you want to show image on both machines, use the copy function on the
socat command to send two copies (one to the other machine, the other to a
new localhost port).

**Comment by rneupane93** [comment]
Thank you for your reply. I had checked that command like yesterday. Its a Linux command, but i wanted to use command in C++ (if any), so that its achievable with just 1 go.

**Comment by rneupane93** [comment]
And yes, one more thing... In the scenario i mentioned earlier, I need to play the video in the system C with the stream sent from system A through B. Like a gateway. Is there anything that you are aware of, which does the trick? Thanks a ton!!!

**Comment by chenxiaoqino** [comment]
Hi, 
1. socat is also available in Windows or OS X; it's also possible to forward the UDP packets in C++ level, but that's simply re-inventing the wheel. Please try socat first.
2. I don't understand why you need a "gateway" yet cannot send packet from A to C directly; please illustrate. If I understand it correctly, the IP address of machine C is not visible to A, in which case you should run socat on machine B.

Cheers

**Comment by rneupane93** [comment]
Its actually just a requirement for a project that i have been working on. An IoT device streaming videos to a cloud server via a gateway. Just for the sake of performance check, I wanted to intentionally make it look like its an A to C but through B. Cant there be a scenario where the server.cpp is changed to use recvfrom and sendto both? Like listening from port 10000 and receiving from the client, the packets, and sending it to a new port like 10001? I tried that but the packet size is changing and thats why i wasnt able to obtain it. I hope this clarifies it.

**Comment by rneupane93** [comment]
Hey!! 
using the following command, like you said, did the trick. It didnt get automated but works with manual entry.
$ sudo socat UDP4-RECVFROM:10000,fork UDP4-SENDTO:127.0.0.1:10001

Thank you so much!!!
