### ISSUE TITLE
Multicast

### ISSUE THREAD

**Issue by chaoticmachinery** [chenxiaoqino/udp-image-streaming#7]
What changes would have to be made to the code to allow for multicasting?

**Comment by chenxiaoqino** [comment]
Can you first try broadcasting into the broadcast address directly? (For example, simply put 192.168.1.255 into the destination IP)

**Comment by chenxiaoqino** [comment]
You need to change to a broadcast UDP socket. i.e. add the `SO_BROADCAST` flag to UDP socket will work.
